# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "LastCommand",
    "Pane",
    "Server",
    "Session",
    "SessionMetadata",
    "Window",
    "WindowMetadata",
]

@typing.final
class LastCommand:
    @property
    def pane_id(self) -> builtins.str: ...
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def read(self) -> builtins.str:
        r"""
        Read the last bash command from this pane.
        
        Returns:
            The last command as a string.
        
        WARNING: using this function might mess up your pane history
        """
    def run(self) -> builtins.bool:
        r"""
        Run the last bash command from this pane.
        
        Returns:
            True on success.
        """

@typing.final
class Pane:
    @property
    def session_name(self) -> builtins.str: ...
    @property
    def window_index(self) -> builtins.int: ...
    @property
    def pane_index(self) -> builtins.int: ...
    @property
    def pane_id(self) -> builtins.str: ...
    @property
    def title(self) -> builtins.str: ...
    @title.setter
    def title(self, value: builtins.str) -> None:
        r"""
        Rename the pane title.
        """
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    @property
    def select(self) -> builtins.bool:
        r"""
        select this pane
        """
    @property
    def clear(self) -> builtins.bool:
        r"""
        clear a panes history
        """
    @property
    def is_alive(self) -> builtins.bool:
        r"""
        Whether the pane is alive.
        """
    @property
    def current_command(self) -> typing.Optional[builtins.str]:
        r"""
        get this shells current command/program
        will be the shell name if no program is active
        
        Returns:
            a string of the current program running on the pane. e.g. `ping -q google.com` will only return `ping`
        """
    @property
    def current_commandline(self) -> typing.Optional[builtins.str]:
        r"""
        get this panes current running command with its arguments
        
        Returns:
            the program ran in the pane with the arguments used. e.g. `ping -q google.com`
        """
    @property
    def last_command(self) -> LastCommand:
        r"""
        get the last command used in this pane 
        
        Returns:
            LastCommand
        """
    def __new__(cls, session_name: builtins.str, window_index: builtins.int, pane_index: builtins.int, pane_id: builtins.str, title: builtins.str, socket: typing.Optional[builtins.str]) -> Pane: ...
    def send_keys(self, keys: builtins.str, enter: builtins.bool = False, clear_first: builtins.bool = False) -> builtins.bool:
        r"""
        send keys to a pane 
        
        Args:
            keys: the keys/commands to send to the pane 
            enter: whether to send enter command and run the command sent
            clear_first: first clear the screen before running the command 
        
        Returns:
            True if successfully sent keys
        """
    def capture(self, trim: builtins.bool = False) -> typing.Optional[builtins.str]:
        r"""
        capture a panes content
        
        Args: 
            trim: remove trailing whitespaces from the capture output
        
        Returns:
            a string of the pane content. any character visible in the pane will ne returned
        """
    def kill(self) -> builtins.bool:
        r"""
        Kill this pane.
        """
    def resize(self, direction: builtins.str, amount: builtins.int) -> builtins.bool:
        r"""
        Resize the pane.
        
        Args:
            direction: One of "left", "right", "up", or "down".
            amount: Number of cells to resize by.
        """
    def split(self, horizontal: builtins.bool = False, command: typing.Optional[builtins.str] = None, keep: builtins.bool = True) -> Pane:
        r"""
        Split this pane and return the new pane.
        
        Args:
            horizontal: Split horizontally if True, vertically otherwise.
            command: Optional command to run in the new pane.
            keep: keep the split running after execution is complete, defaults to true
        """
    def respawn(self, command: typing.Optional[builtins.str] = None, kill: builtins.bool = False) -> builtins.bool:
        r"""
        Respawn the pane.
        
        Args:
            command: Optional command to run after respawning.
            kill: Kill the existing pane process first.
        """
    def bash_shell(self, respawn: builtins.bool = False) -> builtins.bool:
        r"""
        Change this pane to bash.
        
        Args:
            respawn: If True, kill the current pane process and respawn it as bash.
                     If False, run `exec bash` inside the pane.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Server:
    @property
    def sessions(self) -> builtins.list[Session]:
        r"""
        list sessions in this server
        
        Returns:
            A list of Session in this server
        """
    @property
    def is_running(self) -> builtins.bool:
        r"""
        check if a tmux server is running
        
        Returns:
            True if running, False if not
        """
    @property
    def current_socket(self) -> typing.Optional[builtins.str]:
        r"""
        get the tmux socket path for this server
        if a socket was explicitly provided, that is returned.
        otherwise, the default tmux socket path is returned.
        
        Returns:
            str
        """
    def __new__(cls, socket: typing.Optional[builtins.str] = None) -> Server: ...
    def new_session(self, name: builtins.str) -> Session:
        r"""
        create a new session
        
        Returns:
            Session
        """
    def kill(self) -> builtins.bool:
        r"""
        kill a tmux server
        """
    def has_session(self, name: builtins.str) -> builtins.bool:
        r"""
        check if the server contains a session using a session name 
        
        Returns: 
            True if the session name provided exists, False if not
        """
    def start(self) -> builtins.bool:
        r"""
        start a tmux server if none is running
        """

@typing.final
class Session:
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None:
        r"""
        renames a session with the newname provided
        """
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    @property
    def windows(self) -> builtins.list[Window]:
        r"""
        get a list of all windows in a session
        
        Returns:
            Window
        """
    def __new__(cls, name: builtins.str, socket: typing.Optional[builtins.str] = None) -> Session: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def metadata(self) -> SessionMetadata:
        r"""
        get session metadata
        
        Returns:
            SessionMetadata 
        
        Raises: RuntimeError on failure
        """
    def kill(self) -> builtins.bool:
        r"""
        kill this session 
        
        Returns:
            True if the operation is successful
        """

@typing.final
class SessionMetadata:
    @property
    def id(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def created(self) -> builtins.int: ...
    @property
    def attached(self) -> builtins.bool: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def windows(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Window:
    @property
    def session_name(self) -> builtins.str: ...
    @property
    def index(self) -> builtins.int: ...
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def select(self) -> builtins.bool:
        r"""
        select a window if not selected
        
        Returns:
            True if selected, False if the operation failed
        """
    @property
    def panes(self) -> builtins.list[Pane]:
        r"""
        list panes in a window
        
        Returns:
            a list of panes available in this window
        """
    @property
    def metadata(self) -> WindowMetadata:
        r"""
        get window metadata
        
        Returns:
            WindowMetadata
        """
    @property
    def next(self) -> typing.Optional[Window]:
        r"""
        Move to the next tmux window in this session and return it.
        
        Returns:
            The newly selected Window, or None if the operation fails.
        """
    @property
    def previous(self) -> typing.Optional[Window]:
        r"""
        Move to the previous tmux window in this session and return it.
        
        Returns:
            The newly selected Window, or None if the operation fails.
        """
    def __new__(cls, session_name: builtins.str, index: builtins.int, socket: typing.Optional[builtins.str], name: builtins.str) -> Window: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def kill(self) -> builtins.bool:
        r"""
        kill this window
        
        Returns:
            True if killed successfully, False if the operation failed
        """

@typing.final
class WindowMetadata:
    @property
    def index(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def active(self) -> builtins.bool: ...
    @property
    def layout(self) -> builtins.str: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def flags(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

