# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Pane",
    "Server",
    "Session",
    "SessionMetadata",
    "Window",
    "WindowMetadata",
]

@typing.final
class Pane:
    @property
    def session_name(self) -> builtins.str: ...
    @property
    def window_index(self) -> builtins.int: ...
    @property
    def pane_index(self) -> builtins.int: ...
    @property
    def pane_id(self) -> builtins.str: ...
    @property
    def title(self) -> builtins.str: ...
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    @property
    def capture(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, session_name: builtins.str, window_index: builtins.int, pane_index: builtins.int, pane_id: builtins.str, title: builtins.str, socket: typing.Optional[builtins.str]) -> Pane: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Server:
    @property
    def sessions(self) -> builtins.list[Session]:
        r"""
        list sessions in this server
        """
    @property
    def is_running(self) -> builtins.bool:
        r"""
        check if a tmux server is running
        """
    @property
    def current_socket(self) -> typing.Optional[builtins.str]:
        r"""
        get the tmux socket path for this server
        
        if a socket was explicitly provided, that is returned.
        otherwise, the default tmux socket path is returned.
        """
    def __new__(cls, socket: typing.Optional[builtins.str] = None) -> Server: ...
    def new_session(self, name: builtins.str) -> Session:
        r"""
        create a new session
        returns a Session Object
        """
    def kill(self) -> builtins.bool:
        r"""
        kill a tmux server
        """
    def has_session(self, name: builtins.str) -> builtins.bool:
        r"""
        check if the server contains a session
        """
    def start(self) -> builtins.bool:
        r"""
        start a tmux server
        """

@typing.final
class Session:
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None:
        r"""
        renames a session with the newname provided
        """
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, name: builtins.str, socket: typing.Optional[builtins.str] = None) -> Session: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def windows(self) -> builtins.list[Window]:
        r"""
        get a list of all windows in a session
        #[getter]
        """
    def metadata(self) -> SessionMetadata:
        r"""
        get session metadata
        """
    def kill(self) -> builtins.bool: ...

@typing.final
class SessionMetadata:
    @property
    def id(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def created(self) -> builtins.int: ...
    @property
    def attached(self) -> builtins.bool: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def windows(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Window:
    @property
    def session_name(self) -> builtins.str: ...
    @property
    def index(self) -> builtins.int: ...
    @property
    def socket(self) -> typing.Optional[builtins.str]: ...
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def select(self) -> builtins.bool:
        r"""
        select a window if not selected
        """
    @property
    def panes(self) -> builtins.list[Pane]:
        r"""
        list panes in a window
        """
    @property
    def metadata(self) -> WindowMetadata:
        r"""
        get window metadata
        """
    def __new__(cls, session_name: builtins.str, index: builtins.int, socket: typing.Optional[builtins.str], name: builtins.str) -> Window: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def kill(self) -> builtins.bool:
        r"""
        kill window
        """

@typing.final
class WindowMetadata:
    @property
    def index(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def active(self) -> builtins.bool: ...
    @property
    def layout(self) -> builtins.str: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def flags(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

